# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AppleWLoc.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    4,
    '',
    'AppleWLoc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41ppleWLoc.proto\"\x81\x03\n\nWifiDevice\x12\r\n\x05\x62ssid\x18\x01 \x02(\t\x12&\n\x08location\x18\x02 \x01(\x0b\x32\x14.WifiDevice.Location\x1a\xbb\x02\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x03\x12\x11\n\tlongitude\x18\x02 \x01(\x03\x12\x16\n\x0eunknown_value3\x18\x03 \x01(\x03\x12\x16\n\x0eunknown_value4\x18\x04 \x01(\x03\x12\x16\n\x0eunknown_value5\x18\x05 \x01(\x03\x12\x16\n\x0eunknown_value6\x18\x06 \x01(\x03\x12\x16\n\x0eunknown_value7\x18\x07 \x01(\x03\x12\x16\n\x0eunknown_value8\x18\x08 \x01(\x03\x12\x16\n\x0eunknown_value9\x18\t \x01(\x03\x12\x17\n\x0funknown_value10\x18\n \x01(\x03\x12\x17\n\x0funknown_value11\x18\x0b \x01(\x03\x12\x17\n\x0funknown_value12\x18\x0c \x01(\x03\x12\x17\n\x0funknown_value21\x18\x15 \x01(\x03\"\x8d\x01\n\tAppleWLoc\x12\x16\n\x0eunknown_value0\x18\x01 \x01(\x03\x12!\n\x0cwifi_devices\x18\x02 \x03(\x0b\x32\x0b.WifiDevice\x12\x16\n\x0eunknown_value1\x18\x03 \x01(\x05\x12\x1c\n\x14return_single_result\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AppleWLoc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIDEVICE']._serialized_start=20
  _globals['_WIFIDEVICE']._serialized_end=405
  _globals['_WIFIDEVICE_LOCATION']._serialized_start=90
  _globals['_WIFIDEVICE_LOCATION']._serialized_end=405
  _globals['_APPLEWLOC']._serialized_start=408
  _globals['_APPLEWLOC']._serialized_end=549
# @@protoc_insertion_point(module_scope)
